### ISSUE TITLE
Another bug 

### ISSUE THREAD

**Issue by digitalvipers** [martinmiglio/pymemuc#35]
https://prnt.sc/4CKMv5_9vzrx
i tried to run this code below 
the below two lines of code 

from pymemuc import PyMemuc
memuc = PyMemuc()

and got the error below 

runfile('C:/Users/vitalis/untitled0.py', wdir='C:/Users/vitalis')
Traceback (most recent call last):

  File "C:\Users\vitalis\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\vitalis\untitled0.py", line 9, in <module>
    from pymemuc import PyMemuc

  File "C:\Users\vitalis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymemuc\__init__.py", line 8, in <module>
    from .pymemuc import PyMemuc

  File "C:\Users\vitalis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymemuc\pymemuc.py", line 10, in <module>
    class PyMemuc:

  File "C:\Users\vitalis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymemuc\pymemuc.py", line 21, in PyMemuc
    from ._command import (

  File "C:\Users\vitalis\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymemuc\_command.py", line 329, in <module>
    ) -> tuple[int, str]:

TypeError: 'type' object is not subscriptable

please how do i fix it thanks 

screenshot https://prnt.sc/4CKMv5_9vzrx

**Comment by digitalvipers** [comment]
what ide do you use?

**Comment by martinmiglio** [comment]
this issue was fixed in #28 
I just released a new version v0.2.7, upgrading the module with pip should fix this issue on your end
